name: quiz_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  get: ^4.6.5
  flutter_screenutil: ^5.7.0
  go_router: ^7.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/


  fonts:
    - family: BrunoAce
      fonts:
        - asset: assets/fonts/BrunoAce-Regular.ttf

    - family: CrimsonText
      fonts:
        - asset: assets/fonts/CrimsonText-Regular.ttf
